name: piddi
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.11
  - flask
  - python-confluent-kafka>=2.9
  - pydantic>=2.11
  - multiformats
  - rich
  - requests
  - jsonpatch
  - toml
  - tqdm
  - humanize
  # dev
  - python-build>=1.2
  - ipython>=8.13
  - pytest>=8
  - pytest-cov>=6
  - hypothesis>=6.140.2
  - ruff>=0.14,<0.15
  - twine>=4
  - wheel>=0.40
  - black>=26,<27
  - isort>=7,<8
  - pre-commit>=4.5.1,<5
  - bump-my-version>=1.2
